---
- hosts: all
  become: true
  pre_tasks:
    # required for cristian04.cloudwatch-monitoring
    - name: Enable additional RHEL repositories
      command: yum-config-manager --enable rhui-REGION-rhel-server-extras rhui-REGION-rhel-server-optional
    - name: Install unzip package
      yum:
        name: unzip
        update_cache: true
    - name: Install required perl package for cloudwatch module
      yum:
        name: perl-Digest-SHA.x86_64
        update_cache: true
  roles:
    - {role: cristian04.cloudwatch-monitoring,
    sudo: yes,
    cron_specs: "{{ cloudwatch_cron_specs }}"}
    - ansible-os-rhel-7
